// GENERATED by _Kit\sync-kit.ps1 - do not edit by hand.
// Re-run:  .\sync-kit.ps1 -Project GeneralMeeting
//
// Lists only the namespaces this project owns. Adding a namespace means
// adding the folder under i18n\ and re-running the sync.

import faGeneralMeeting from '@/i18n/general-meeting/fa.json';
import enGeneralMeeting from '@/i18n/general-meeting/en.json';

export const DOMAIN_NAMESPACES = {
  fa: {
  'general-meeting': faGeneralMeeting,
  },
  en: {
  'general-meeting': enGeneralMeeting,
  },
} as const;
